package com.example.omrscanner.database.entities;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * One teacher-marked answer for a single ECDC competency, for one student in
 * one assessment period (BOSY / MOSY / EOSY).
 *
 * Deliberately has NO foreign keys. Both possible parents get rewritten by
 * routine syncs and a CASCADE would silently delete the teacher's work:
 *   - ecdc_competencies is wiped and re-inserted on every "Sync ECCD".
 *   - student_lrn / classes use REPLACE inserts, which delete-then-insert
 *     (a new autogenerated id, cascading to any child rows).
 * So the student is identified by (class_id, lrn) — the same natural key
 * student_lrn itself is unique on — and the competency by the server's own id.
 */
@Entity(
        tableName = "ecdc_responses",
        indices = {
                @Index(value = {"class_id", "lrn", "period", "competency_id"}, unique = true)
        }
)
public class EcdcResponseEntity {

    public static final String STATUS_PRESENT = "PRESENT";
    public static final String STATUS_NOT_PRESENT = "NOT_PRESENT";
    public static final String STATUS_NOT_TESTED = "NOT_TESTED";

    @PrimaryKey(autoGenerate = true)
    public int id;

    @NonNull
    @ColumnInfo(name = "class_id")
    public String classId = "";

    @NonNull
    @ColumnInfo(name = "lrn")
    public String lrn = "";

    /** "BOSY", "MOSY" or "EOSY". */
    @NonNull
    @ColumnInfo(name = "period")
    public String period = "";

    /** The server's ecdc_competencies.id (plain int, not a foreign key — see class doc). */
    @ColumnInfo(name = "competency_id")
    public int competencyId;

    /** One of the STATUS_* constants. */
    @NonNull
    @ColumnInfo(name = "status")
    public String status = STATUS_NOT_TESTED;

    @ColumnInfo(name = "updated_at")
    public long updatedAt;
}